-- TASK 1: RoomInvite Migration Documentation
-- This file documents the migration that will be generated by Prisma

-- Step 1: Create RoomInviteStatus enum
CREATE TYPE "RoomInviteStatus" AS ENUM ('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', 'EXPIRED');

-- Step 2: Create RoomInvite table
CREATE TABLE "RoomInvite" (
    "id" TEXT NOT NULL,
    "roomId" TEXT NOT NULL,
    "inviterId" TEXT NOT NULL,
    "inviteeId" TEXT NOT NULL,
    "status" "RoomInviteStatus" NOT NULL DEFAULT 'PENDING',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "metadata" JSONB,

    CONSTRAINT "RoomInvite_pkey" PRIMARY KEY ("id")
);

-- Step 3: Create foreign key constraints
ALTER TABLE "RoomInvite" ADD CONSTRAINT "RoomInvite_inviterId_fkey" 
    FOREIGN KEY ("inviterId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "RoomInvite" ADD CONSTRAINT "RoomInvite_inviteeId_fkey" 
    FOREIGN KEY ("inviteeId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Step 4: Create indexes for performance
CREATE INDEX "RoomInvite_roomId_idx" ON "RoomInvite"("roomId");
CREATE INDEX "RoomInvite_inviteeId_idx" ON "RoomInvite"("inviteeId");
CREATE INDEX "RoomInvite_inviterId_idx" ON "RoomInvite"("inviterId");
CREATE INDEX "RoomInvite_status_idx" ON "RoomInvite"("status");
CREATE INDEX "RoomInvite_expiresAt_idx" ON "RoomInvite"("expiresAt");
CREATE INDEX "RoomInvite_roomId_inviteeId_status_idx" ON "RoomInvite"("roomId", "inviteeId", "status");

-- OPTIONAL: Partial unique index (PostgreSQL only) for preventing duplicate PENDING invites
-- This is more efficient than checking in application code
-- Uncomment if you want database-level constraint:

-- CREATE UNIQUE INDEX "RoomInvite_roomId_inviteeId_pending_unique" 
--     ON "RoomInvite"("roomId", "inviteeId") 
--     WHERE "status" = 'PENDING';

-- NOTE: The application code already handles this validation in createInvite()
-- to provide better error messages. The partial unique index is optional for extra safety.

-- To run this migration:
-- 1. Make sure schema.prisma is updated
-- 2. Run: npx prisma migrate dev --name add_room_invite_table
-- 3. Prisma will generate migration SQL automatically
